#!/stage1/busybox sh
export _PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

while ! busybox test -d /sys/dev/block/179:0 ; do
	echo "Waiting for internal mmc..."
	busybox sleep 1
done

/lvm/sbin/lvm vgscan --mknodes --ignorelockingfailure
/lvm/sbin/lvm vgchange -aly --ignorelockingfailure

busybox mount -t ext4 /dev/block/mmcblk0p13 /system
busybox mount -t ext4 /dev/block/mmcblk0p15 /cache

image=/stage1/ramdisk.img

if busybox test -e /cache/.startrecovery || busybox grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot so dd param.lfs to work around missing proprietary driver
	busybox bzcat /stage1/param.bz2 | busybox dd of=/dev/block/mmcblk0p9 bs=128K

	busybox rm -fr /cache/.startrecovery
	image=/stage1/ramdisk-recovery.img

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
elif ! busybox test -e /system/build.prop ; then
	# emergency boot
	busybox umount /cache
	#make_ext4fs /dev/block/mmcblk0p15
	busybox mount -t ext4 /dev/block/mmcblk0p15 /cache
	busybox mkdir /cache/recovery

	busybox mount -t vfat /dev/block/mmcblk1p1 /sdcard

	UPDATE=$(busybox cat /sdcard/cyanogenmod.cfg)

	if busybox test -n "$UPDATE" ; then
		busybox echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
	fi

	busybox umount /sdcard
	busybox rmdir /sdcard

	image=/stage1/ramdisk-recovery.img

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

busybox umount /cache
busybox umount /system

busybox zcat $image | busybox cpio -i

if busybox grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	busybox cp lpm.rc init.rc
	busybox rm init.venturi.rc
fi

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt

busybox mkdir /emmc
busybox mount -t vfat /dev/block/mmcblk0p17 /emmc
busybox cp /boot.txt /emmc/boot.txt
busybox umount /emmc
busybox rmdir /emmc

busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
